import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  wrapper: {
    backgroundColor: '#20212E',
    width: '100%',
    height: '100%',
    zIndex: 2,
  },
  background: {
    width: '100%',
    height: '30%',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
    zIndex: 1,
  },
  container: {
    paddingHorizontal: 15,
    paddingTop: 55,
    paddingBottom: 52,
    alignItems: 'center',
    zIndex: 3,
  },
  title: {
    fontFamily: 'Raleway-Black',
    fontSize: 35,
    lineHeight: 42,
    color: 'white',
    marginBottom: 25,
  },
  buttonActive: {
    fontFamily: 'Raleway-Bold',
    fontSize: 14,
    color: '#FFFFFF',
    textTransform: 'uppercase',
    backgroundColor: '#BC181E',
    height: 35,
    width: 130,
    textAlign: 'center',
    textAlignVertical: 'center',
    marginTop: 15,
  },
  input: {
    fontFamily: 'Raleway-Regular',
    color: '#FFFFFF',
    borderBottomWidth: 2,
    borderBottomColor: '#FBF6F0',
    width: 300,
    marginBottom: 15,
    fontSize: 16,
    height: 45,
  },
  flatlist: {
    marginTop: 10,
    marginBottom: 20,
  },
  types: {
    width: 300,
    alignItems: 'center',
    marginTop: 20,
  },
  type: {
    width: 300,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    marginBottom: 10,
  },
  typeImage: {
    marginRight: 10,
    paddingTop: 3,
  },
  typeTextGreen: {
    fontFamily: 'Raleway-Regular',
    fontSize: 15,
    color: '#FFFFFF',
  },
  typeTextYellow: {
    fontFamily: 'Raleway-Regular',
    fontSize: 15,
    color: '#FFFFFF',
  },
  typeTextBlue: {
    fontFamily: 'Raleway-Regular',
    fontSize: 15,
    color: '#333333',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  prioritys: {
    width: 300,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  priority: {
    width: 90,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#949494',
    marginBottom: 10,
  },
  priorityImage: {
    paddingTop: 3,
  },
  priorityTextGreen: {
    fontFamily: 'Raleway-Regular',
    fontSize: 15,
    color: '#FFFFFF',
  },
  priorityTextYellow: {
    fontFamily: 'Raleway-Regular',
    fontSize: 15,
    color: '#FFFFFF',
  },
  priorityTextBlue: {
    fontFamily: 'Raleway-Regular',
    fontSize: 15,
    color: '#333333',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
});

export default styles;
